version: '3.8'

services:
  transcription-search:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount the data directory to persist processed files
      - ./data:/app/data
      # Mount podcast files
      - ./podcast:/app/podcast
      # Mount temp directory for processing
      - ./temp_podcasts:/app/temp_podcasts
    environment:
      - ENVIRONMENT=docker
      - LOG_LEVEL=INFO
      - MAX_MEMORY_MB=512
      - BATCH_SIZE=10
    command: >
      sh -c "
        echo 'Processing first 10 podcast episodes...' &&
        python process_podcasts.py &&
        echo 'Starting search API server...' &&
        uvicorn core.search_api:app --host 0.0.0.0 --port 8000 --reload
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s 