global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'transcription-api'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/api/v1/metrics/prometheus'
    scrape_interval: 10s 